name: Simple Actions
on:
  push:
    branches:
      - master
      - devop
      - feature  
env: 
  MY_VAR: ${{secrets.MY_VAR}} 

jobs:
  ownpush-without-checkout: 
    runs-on: ubuntu-latest
    steps:
      - name : pushing random text
        run: |
          pwd
          ls -a 
          git init 
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "demo@gmail.com"
          git config --global user.name "anonymous"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a 
          echo $RANDOM >> random.txt
          ls -a 
          git add -A 
          git commit -m "random file"
          git push 
          
    

  custome-env-variables:
    env: 
      VAR3 : "Available in this job"
    runs-on: ubuntu-latest
    steps:
      - env: 
          VAR2 : "Available only in this step"
        run: |
          echo {{$VAR3}}
          echo {{$VAR2}}
          echo ${{env.MY_VAR}}
          echo $MY_VAR
      - name: not available here
        run: echo {{$VAR2}}

  simple-git-action:
    runs-on: ubuntu-latest
    steps:
      - name: getting our local repo
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTION
          echo $GITHUB_ACTIONS
          echo $GITHUB_ACTOR
          echo $GITHUB_REF
          
          
          
