name: Simple Actions
on:
  push:
  pull_request:
    types:
      - opened
      - closed
      - reopened
  issues:
    types:
      - opened
      - closed
  schedule:
    - cron: "0/5 * 8-29 10 5"
    - cron: "0/6 * * * * "
    
jobs:
  simple-git-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: getting our local repo
        run: |
          pwd
          ls 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          git log --oneline
          
          
          
