name: Simple Actions
on: [push]
jobs:
  simple-git-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Actions
        id: gtu
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: naga sree
      - name: Output getting
        run: echo "${{steps.gtu.outputs.time}}"
