name: Simple Actions
on:
  pull_request:
    branches:
      - master
      - devop
      - feature  
env: 
  MY_VAR: ${{secrets.MY_VAR}} 

jobs:

  custome-env-variables:
    env: 
      VAR3 : "Available in this job"
    runs-on: ubuntu-latest
    steps:
      - env: 
          VAR2 : "Available only in this step"
        run: |
          echo {{$VAR3}}
          echo {{$VAR2}}
          echo ${{env.MY_VAR}}
          echo $MY_VAR
      - name: not available here
        run: echo {{$VAR2}}
      - uses: actions/checkout@v1
      - name: enc and dec
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secret.json.gpg
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
      - name: checking
        run: cat $HOME/secret.json

  simple-git-action:
    runs-on: ubuntu-latest
    steps:
      - name: getting our local repo
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTION
          echo $GITHUB_ACTIONS
          echo $GITHUB_ACTOR
          echo $GITHUB_REF
          
          
          
