name: Simple Actions
on: [push]
jobs:
  simple-git-action:
    runs-on: windows-latest
    steps:
      - name: Simple Actions
        id: gtu
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: naga sree
      - name: Output getting
        run: |
          
          git clone https://github.com/Nagasree2000/alpha.git
          git add .
          git ls-files
