name: Container
on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine3.15
    steps:
      - name: nodeversio
        run: node -v 
      - name: docker in step
        uses: docker://node:14-buster-slim 
        with:
          entrypoint: '/bin/echo'
          args: 'hello' 
      - name: docker in step
        uses: docker://node:14-buster-slim 
        with:
          entrypoint: '/c/Program Files/nodejs/node'
          args: -v 