name: Shell Commands
on: [push]

jobs:
  functions:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push'
    steps:
      - name: functions
        continue-on-error: true
        run: |
          echo ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          echo ${{ startsWith('Hello', 'He') }}
          echo ${{ endsWith('Hello', 'o') }}
          echo ${{ format('Hello {0} {1} {2}','na','mo','rs') }}
          echo ${{continue-on-error}}
      - name: checking status
        if: failure()
        run: echo "failure occured"
      - name: testing always
        timeout-minutes: 360
        if: always()
        run: echo "this step runs always"
      - name: success Commands
        if: success()
        run: echo "success"
      
          
      
