name: Shell Commands
on: [push]
jobs:
  functions:
    runs-on: ubuntu-18.04
    steps:
      - name: functions
        run: |
          echo ${{ contains('Hello','lo') }}
          echo ${{ startsWith('Hello', 'He') }}
          echo ${{ endsWith('Hello', 'o') }}
          echo ${{ format('Hello {0} {1} {2}','na','mo','rs') }}
          fruits: [ { snames: apple, quantity: 1 },
          { snames: orange, quantity: 2 },
          { snames: pear, quantity: 1 } ]
          echo ${{ fruits.*.snames }}
  
          
      
