name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: echo a string
        run: |
          git init
          ls -a 
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git clone "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          ls -a
          git config --global user.email "anonymous@gmail.com"
          git config --global user.name "anonymous"
          ls -a 
          echo $RANDOM >> new.txt
          ls -a 
          git add -A 
          git commit -m "added again"
          git push origin master
      
