name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: echo versions
        run: |
          node -v
          npm -v
      - name: pytho Commands
        run: |
            import platform
            print(platform.processor())
        shell: python