name: Shell Commands
on: [push]
 
jobs:
  functions:
    strategy: 
      matrix:
        fruits: [{snames: app, quant: 20},{snames: baan, quant: 21},{snames: pineapp, quant: 22}]
      fail-fast: true
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: functions
        continue-on-error: true
        run: |
          echo ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          echo ${{ startsWith('Hello', 'He') }}
          echo ${{ endsWith('Hello', 'o') }}
          echo ${{ format('Hello {0} {1} {2}','na','mo','rs') }}
          echo ${{ matrix.fruits.*.snames}}

      - name: setup-node 
        run: node -v
      - name: using setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 6
      - name: success Commands
        run: node -v

          
      
