name: Shell Commands
on: [push]
 
jobs:
  functions:
    strategy: 
      matrix:
        nodev: [6,16,18]
        os: [macos-latest,windows-latest]
      fail-fast: true
    runs-on: ${{matrix.os}}
    if: github.event_name == 'push'
    steps:
      - name: functions
        continue-on-error: true
        run: |
          echo ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          echo ${{ startsWith('Hello', 'He') }}
          echo ${{ endsWith('Hello', 'o') }}
          echo ${{ format('Hello {0} {1} {2}','na','mo','rs') }}
          

      - name: setup-node 
        run: node -v
      - name: using setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.nodev}}
      - name: success Commands
        run: node -v

          
      
