name: Shell Commands
on: [push]

jobs:
  Dockercontainers:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine3.15 
    steps:
      - name: verifying docker 
        run: |
          node -v
          echo ${{runner.os}}
          cat /etc/os-release

        
        
    

          
      
