name: Shell Commands
on: [push]
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: functions
        run:  |
          echo contains('Hello','lo')
          echo startsWith('Hello','He')
          echo endsWith('Hello','o')
          echo format('Hello {0} {1} {2}','na','mo','rs')
          fruits: [ { snames: apple, quantity: 1 },
          { snames: orange, quantity: 2 },
          { snames: pear, quantity: 1 } ]
          echo fruits.*.snames
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
      
